# File: /debian-node/Makefile
# Project: images
# File Created: 07-04-2023 09:18:49
# Author: Clay Risser <email@clayrisser.com>
# -----
# Last Modified: 04-08-2023 07:27:02
# Modified By: Clay Risser <email@clayrisser.com>
# -----
# BitSpur (c) Copyright 2021 - 2023
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

include $(MKPM)/mkpm
include $(MKPM)/gnu
include $(PROJECT_ROOT)/shared.mk

export NAME ?= debian-node
export VERSION ?= 18.16.1

include $(MKPM)/docker
