# File: /base/docker-build.yaml
# Project: ci-images
# File Created: 06-10-2021 14:23:56
# Author: Clay Risser <email@clayrisser.com>
# -----
# Last Modified: 06-10-2021 14:30:53
# Modified By: Clay Risser <email@clayrisser.com>
# -----
# Silicon Hills LLC (c) Copyright 2021
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "2"

services:
  main:
    image: ${IMAGE}:${TAG}
    build:
      context: context
      dockerfile: Dockerfile
  major:
    extends: main
    image: ${IMAGE}:${MAJOR}
  minor:
    extends: main
    image: ${IMAGE}:${MAJOR}.${MINOR}
  patch:
    extends: main
    image: ${IMAGE}:${MAJOR}.${MINOR}.${PATCH}
